name: authentication_servicee
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_frog: ^0.0.1-dev

  json_annotation: ^4.6.0
  postgres: ^2.4.6
  riverpod: ^1.0.3

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
